### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by jdev082** [platinum-browser/Platinum-Legacy#10]
**Nightly builds are provided here, these builds are tied to the main branch and not individual releases. Provided for Windows x64 only**

[20221112](https://dl.jaydendev.repl.co/platinum-0.20221112.52.exe)

**Comment by jdev082** [comment]
v0.20221112.52 has been release *unofficially*. ^

**Comment by redstone-dev** [comment]
I might provide these myself.
