### ISSUE TITLE
[Feature Request]: Make GitHub actions make a binary exe of the browser

### ISSUE THREAD

**Issue by michaeIwave** [platinum-browser/Platinum-Legacy#15]
### Is your feature request related to a problem? Please describe.

The only release we have right now is a testing release without any .exe or .app files and that is annoying because we have to do it ourselves 

### Describe the solution you would like!

I think GitHub actions can automatically make a build every week so you don’t have to do anything

### Describe alternatives you have considered.

You could probably do the building and uploading yourself

**Comment by jdev082** [comment]
@michaeIwave [This already exists.](https://github.com/platinum-browser/Platinum/blob/develop/.github/workflows/build.yml)
