### ISSUE TITLE
[Feature Request]: Add instructions on how to compile manually.

### ISSUE THREAD

**Issue by UniqueName12345** [platinum-browser/Platinum-Legacy#3]
### Is your feature request related to a problem? Please describe.

What if you don't want to install it? What if you don't have the required permissions to? What if you want to contribute?

### Describe the solution you would like!

Add instructions on how to compile manually in either the README or the wiki.

**Comment by michaeleldar** [comment]
It's the same as it is on Catalyst, but I'll make a pull request now anyway.

Done!

**Comment by michaeleldar** [comment]
Can someone please close this...

**Comment by redstone-dev** [comment]
Sorry, I will now!
