### ISSUE TITLE
[Bug]: Platinum shows the bookmark bar even when it's turned off.

### ISSUE THREAD

**Issue by michaeleldar** [platinum-browser/Platinum-Legacy#5]
### Steps to reproduce the issue?

What I did was:
I build Platinum from source, then added two different bookmarks. They showed up, even when I had turned them off.

Note: When I reopened the browser, they were hidden again, but as soon as I added another they all showed up again.
Note: I'll try to fix this as well.

### What happened?

I expected my bookmarks to be hidden until I enabled them.

### Version

Dev from commit 8c7f869

**Comment by michaeleldar** [comment]
Fixed in this pull request: https://github.com/redstone-scratch/Platinum/pull/4

**Comment by jdev082** [comment]
I'm using the latest source code and can't reproduce this bug.

**Comment by michaeleldar** [comment]
> I'm using the latest source code and can't reproduce this bug.

It got fixed in commit 2cfa290. If you're using that version, then yes it got fixed. Also this might be broken in Catalyst too, so try to reproduce it there.
